### PR TITLE
#2 - Modification needed in xcunsign,xcrestore script for macOS Sierra

### PR DESCRIPTION
**Pull request by kaustubhkabra**
This commit will fix issue issue #2.

### CODE REVIEW

**Comment by johntmcintosh** [comment]
@kaustubh-kabra thanks for the PR! Can you confirm for me that you are able to run `xcrestore` after `xcunsign` and that it restores Xcode correctly on Sierra with this change? 

If you have [`fastlane`](https://fastlane.tools) installed, the best test would be to run `fastlane run verify_xcode 8.0` after unsigning and then restoring. If the verify passes successfully, we can be confident that the restore worked as intended.

**Comment by kaustubhkabra** [comment]
I don't use Fastlane but I confirm restore is working fine after unsign -
screen shot 2016-10-13 at 8 07 01 pm

**Comment by johntmcintosh** [comment]
Awesome, thanks for the confirmation!

**Comment by kaustubhkabra** [comment]
Cheers !

**Pull request merged**
